
services:
  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8080:80"
    environment:
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=secretpassword
    volumes:
      - ./nagios/etc/conf.d:/opt/nagios/etc/conf.d
